server:
  port: 9999

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/sdp;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    initialize: true
  h2:
    console:
      enabled: true
      path: /db
      web-allow-others: true
      trace: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
