version: '3.3'
services:
  vue-admin-beautiful:
    build: ./
    restart: always
    container_name: vue-admin-beautiful
    image: vue-admin-beautiful
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - /var/nginx:/var/data #挂载 Nginx 文件
    ports:
      - "80:80"
